pub(super) fn duration_unit_pattern(
    unit: &str,
    display: &str,
    singular: bool,
) -> Option<(&'static str, &'static str)> {
    let pattern = match (unit, display, singular) {
        ("year", "long", true) => (" ", "year"),
        ("year", "long", false) => (" ", "years"),
        ("year", "short", true) => (" ", "yr"),
        ("year", "short", false) => (" ", "yrs"),
        ("year", "narrow", _) => ("", "y"),
        ("month", "long", true) => (" ", "month"),
        ("month", "long", false) => (" ", "months"),
        ("month", "short", true) => (" ", "mo"),
        ("month", "short", false) => (" ", "mos"),
        ("month" | "minute", "narrow", _) => ("", "m"),
        ("week", "long", true) => (" ", "week"),
        ("week", "long", false) => (" ", "weeks"),
        ("week", "short", true) => (" ", "wk"),
        ("week", "short", false) => (" ", "wks"),
        ("week", "narrow", _) => ("", "w"),
        ("day", "long" | "short", true) => (" ", "day"),
        ("day", "long" | "short", false) => (" ", "days"),
        ("day", "narrow", _) => ("", "d"),
        ("hour", "long", true) => (" ", "hour"),
        ("hour", "long", false) => (" ", "hours"),
        ("hour", "short", true) => (" ", "hr"),
        ("hour", "short", false) => (" ", "hrs"),
        ("hour", "narrow", _) => ("", "h"),
        ("minute", "long", true) => (" ", "minute"),
        ("minute", "long", false) => (" ", "minutes"),
        ("minute", "short", _) => (" ", "min"),
        ("second", "long", true) => (" ", "second"),
        ("second", "long", false) => (" ", "seconds"),
        ("second", "short", _) => (" ", "sec"),
        ("second", "narrow", _) => ("", "s"),
        ("millisecond", "long", true) => (" ", "millisecond"),
        ("millisecond", "long", false) => (" ", "milliseconds"),
        ("millisecond", "short" | "narrow", _) => (" ", "ms"),
        ("microsecond", "long", true) => (" ", "microsecond"),
        ("microsecond", "long", false) => (" ", "microseconds"),
        ("microsecond", "short" | "narrow", _) => (" ", "μs"),
        ("nanosecond", "long", true) => (" ", "nanosecond"),
        ("nanosecond", "long", false) => (" ", "nanoseconds"),
        ("nanosecond", "short" | "narrow", _) => (" ", "ns"),
        _ => return None,
    };
    Some(pattern)
}
