use crate::api::native_call::NativeCallTarget;

use super::NativeFunctionKind;

impl NativeFunctionKind {
    pub(super) const fn from_call_target(target: NativeCallTarget) -> Self {
        match target {
            NativeCallTarget::Array => Self::Array,
            NativeCallTarget::ArrayConcat => Self::ArrayConcat,
            NativeCallTarget::ArrayIncludes => Self::ArrayIncludes,
            NativeCallTarget::ArrayIndexOf => Self::ArrayIndexOf,
            NativeCallTarget::ArrayIsArray => Self::ArrayIsArray,
            NativeCallTarget::ArrayJoin => Self::ArrayJoin,
            NativeCallTarget::ArrayLastIndexOf => Self::ArrayLastIndexOf,
            NativeCallTarget::ArrayPop => Self::ArrayPop,
            NativeCallTarget::ArrayPush => Self::ArrayPush,
            NativeCallTarget::ArrayReverse => Self::ArrayReverse,
            NativeCallTarget::ArrayShift => Self::ArrayShift,
            NativeCallTarget::ArraySlice => Self::ArraySlice,
            NativeCallTarget::ArrayUnshift => Self::ArrayUnshift,
            NativeCallTarget::Boolean => Self::Boolean,
            NativeCallTarget::ErrorConstructor(name) => Self::ErrorConstructor(name),
            NativeCallTarget::Function => Self::Function,
            NativeCallTarget::FunctionPrototypeCall => Self::FunctionPrototypeCall,
            NativeCallTarget::JsonParse => Self::JsonParse,
            NativeCallTarget::JsonStringify => Self::JsonStringify,
            NativeCallTarget::MathAbs => Self::MathAbs,
            NativeCallTarget::MathAcos => Self::MathAcos,
            NativeCallTarget::MathAcosh => Self::MathAcosh,
            NativeCallTarget::MathAsin => Self::MathAsin,
            NativeCallTarget::MathAsinh => Self::MathAsinh,
            NativeCallTarget::MathAtan => Self::MathAtan,
            NativeCallTarget::MathAtan2 => Self::MathAtan2,
            NativeCallTarget::MathAtanh => Self::MathAtanh,
            NativeCallTarget::MathCbrt => Self::MathCbrt,
            NativeCallTarget::MathCeil => Self::MathCeil,
            NativeCallTarget::MathClz32 => Self::MathClz32,
            NativeCallTarget::MathCos => Self::MathCos,
            NativeCallTarget::MathCosh => Self::MathCosh,
            NativeCallTarget::MathExp => Self::MathExp,
            NativeCallTarget::MathExpm1 => Self::MathExpm1,
            NativeCallTarget::MathFloor => Self::MathFloor,
            NativeCallTarget::MathFround => Self::MathFround,
            NativeCallTarget::MathHypot => Self::MathHypot,
            NativeCallTarget::MathImul => Self::MathImul,
            NativeCallTarget::MathLog => Self::MathLog,
            NativeCallTarget::MathLog10 => Self::MathLog10,
            NativeCallTarget::MathLog1p => Self::MathLog1p,
            NativeCallTarget::MathLog2 => Self::MathLog2,
            NativeCallTarget::MathMax => Self::MathMax,
            NativeCallTarget::MathMin => Self::MathMin,
            NativeCallTarget::MathPow => Self::MathPow,
            NativeCallTarget::MathRandom => Self::MathRandom,
            NativeCallTarget::MathRound => Self::MathRound,
            NativeCallTarget::MathSign => Self::MathSign,
            NativeCallTarget::MathSin => Self::MathSin,
            NativeCallTarget::MathSinh => Self::MathSinh,
            NativeCallTarget::MathSqrt => Self::MathSqrt,
            NativeCallTarget::MathTan => Self::MathTan,
            NativeCallTarget::MathTanh => Self::MathTanh,
            NativeCallTarget::MathTrunc => Self::MathTrunc,
            NativeCallTarget::Number => Self::Number,
            NativeCallTarget::Object => Self::Object,
            NativeCallTarget::ObjectDefineProperty => Self::ObjectDefineProperty,
            NativeCallTarget::ObjectGetOwnPropertyDescriptor => {
                Self::ObjectGetOwnPropertyDescriptor
            }
            NativeCallTarget::ObjectGetOwnPropertyNames => Self::ObjectGetOwnPropertyNames,
            NativeCallTarget::ObjectGetPrototypeOf => Self::ObjectGetPrototypeOf,
            NativeCallTarget::ObjectHasOwn => Self::ObjectHasOwn,
            NativeCallTarget::ObjectKeys => Self::ObjectKeys,
            NativeCallTarget::Promise => Self::Promise,
            NativeCallTarget::PromiseResolve => Self::PromiseResolve,
            NativeCallTarget::PromiseReject => Self::PromiseReject,
            NativeCallTarget::PromiseThen => Self::PromiseThen,
            NativeCallTarget::PromiseCatch => Self::PromiseCatch,
            NativeCallTarget::RegExp => Self::RegExp,
            NativeCallTarget::RegExpPrototypeTest => Self::RegExpPrototypeTest,
            NativeCallTarget::String => Self::String,
            NativeCallTarget::Symbol => Self::Symbol,
        }
    }

    pub(super) const fn to_call_target(self) -> Option<NativeCallTarget> {
        match self {
            Self::Array => Some(NativeCallTarget::Array),
            Self::ArrayConcat => Some(NativeCallTarget::ArrayConcat),
            Self::ArrayIncludes => Some(NativeCallTarget::ArrayIncludes),
            Self::ArrayIndexOf => Some(NativeCallTarget::ArrayIndexOf),
            Self::ArrayIsArray => Some(NativeCallTarget::ArrayIsArray),
            Self::ArrayJoin => Some(NativeCallTarget::ArrayJoin),
            Self::ArrayLastIndexOf => Some(NativeCallTarget::ArrayLastIndexOf),
            Self::ArrayPop => Some(NativeCallTarget::ArrayPop),
            Self::ArrayPush => Some(NativeCallTarget::ArrayPush),
            Self::ArrayReverse => Some(NativeCallTarget::ArrayReverse),
            Self::ArrayShift => Some(NativeCallTarget::ArrayShift),
            Self::ArraySlice => Some(NativeCallTarget::ArraySlice),
            Self::ArrayUnshift => Some(NativeCallTarget::ArrayUnshift),
            Self::AsyncFunction
            | Self::BoundFunction(_)
            | Self::Eval
            | Self::FunctionPrototypeBind
            | Self::ObjectPrototypeHasOwnProperty
            | Self::ObjectPrototypePropertyIsEnumerable
            | Self::PromiseResolver { .. } => None,
            Self::Boolean => Some(NativeCallTarget::Boolean),
            Self::ErrorConstructor(name) => Some(NativeCallTarget::ErrorConstructor(name)),
            Self::Function => Some(NativeCallTarget::Function),
            Self::FunctionPrototypeCall => Some(NativeCallTarget::FunctionPrototypeCall),
            Self::JsonParse => Some(NativeCallTarget::JsonParse),
            Self::JsonStringify => Some(NativeCallTarget::JsonStringify),
            Self::MathAbs => Some(NativeCallTarget::MathAbs),
            Self::MathAcos => Some(NativeCallTarget::MathAcos),
            Self::MathAcosh => Some(NativeCallTarget::MathAcosh),
            Self::MathAsin => Some(NativeCallTarget::MathAsin),
            Self::MathAsinh => Some(NativeCallTarget::MathAsinh),
            Self::MathAtan => Some(NativeCallTarget::MathAtan),
            Self::MathAtan2 => Some(NativeCallTarget::MathAtan2),
            Self::MathAtanh => Some(NativeCallTarget::MathAtanh),
            Self::MathCbrt => Some(NativeCallTarget::MathCbrt),
            Self::MathCeil => Some(NativeCallTarget::MathCeil),
            Self::MathClz32 => Some(NativeCallTarget::MathClz32),
            Self::MathCos => Some(NativeCallTarget::MathCos),
            Self::MathCosh => Some(NativeCallTarget::MathCosh),
            Self::MathExp => Some(NativeCallTarget::MathExp),
            Self::MathExpm1 => Some(NativeCallTarget::MathExpm1),
            Self::MathFloor => Some(NativeCallTarget::MathFloor),
            Self::MathFround => Some(NativeCallTarget::MathFround),
            Self::MathHypot => Some(NativeCallTarget::MathHypot),
            Self::MathImul => Some(NativeCallTarget::MathImul),
            Self::MathLog => Some(NativeCallTarget::MathLog),
            Self::MathLog10 => Some(NativeCallTarget::MathLog10),
            Self::MathLog1p => Some(NativeCallTarget::MathLog1p),
            Self::MathLog2 => Some(NativeCallTarget::MathLog2),
            Self::MathMax => Some(NativeCallTarget::MathMax),
            Self::MathMin => Some(NativeCallTarget::MathMin),
            Self::MathPow => Some(NativeCallTarget::MathPow),
            Self::MathRandom => Some(NativeCallTarget::MathRandom),
            Self::MathRound => Some(NativeCallTarget::MathRound),
            Self::MathSign => Some(NativeCallTarget::MathSign),
            Self::MathSin => Some(NativeCallTarget::MathSin),
            Self::MathSinh => Some(NativeCallTarget::MathSinh),
            Self::MathSqrt => Some(NativeCallTarget::MathSqrt),
            Self::MathTan => Some(NativeCallTarget::MathTan),
            Self::MathTanh => Some(NativeCallTarget::MathTanh),
            Self::MathTrunc => Some(NativeCallTarget::MathTrunc),
            Self::Number => Some(NativeCallTarget::Number),
            Self::Object => Some(NativeCallTarget::Object),
            Self::ObjectDefineProperty => Some(NativeCallTarget::ObjectDefineProperty),
            Self::ObjectGetPrototypeOf => Some(NativeCallTarget::ObjectGetPrototypeOf),
            Self::ObjectGetOwnPropertyDescriptor => {
                Some(NativeCallTarget::ObjectGetOwnPropertyDescriptor)
            }
            Self::ObjectGetOwnPropertyNames => Some(NativeCallTarget::ObjectGetOwnPropertyNames),
            Self::ObjectHasOwn => Some(NativeCallTarget::ObjectHasOwn),
            Self::ObjectKeys => Some(NativeCallTarget::ObjectKeys),
            Self::Promise => Some(NativeCallTarget::Promise),
            Self::PromiseResolve => Some(NativeCallTarget::PromiseResolve),
            Self::PromiseReject => Some(NativeCallTarget::PromiseReject),
            Self::PromiseThen => Some(NativeCallTarget::PromiseThen),
            Self::PromiseCatch => Some(NativeCallTarget::PromiseCatch),
            Self::RegExp => Some(NativeCallTarget::RegExp),
            Self::RegExpPrototypeTest => Some(NativeCallTarget::RegExpPrototypeTest),
            Self::String => Some(NativeCallTarget::String),
            Self::Symbol => Some(NativeCallTarget::Symbol),
        }
    }
}
