mod builtins;
mod core;
mod default_global_bindings;
mod function;

pub(super) use default_global_bindings::DEFAULT_GLOBAL_BINDING_NAMES;

pub(in crate::runtime::native) use builtins::{
    CollectionIterationTarget, FINALIZATION_REGISTRY_NAME, MAP_NAME, RegExpCallMode, SET_NAME,
    WEAK_MAP_NAME, WEAK_REF_NAME, WEAK_SET_NAME, number_intrinsic_property,
};
pub(in crate::runtime::native) use function::{
    ARRAY_BUFFER_NAME, ARRAY_NAME, ATOMICS_NAME, BIGINT_AS_INT_N_NAME, BIGINT_AS_UINT_N_NAME,
    BIGINT_NAME, BIGINT_PROTOTYPE_TO_LOCALE_STRING_NAME, BIGINT_PROTOTYPE_TO_STRING_NAME,
    BIGINT_PROTOTYPE_VALUE_OF_NAME, BOOLEAN_NAME, BOOLEAN_PROTOTYPE_TO_STRING_NAME,
    BOOLEAN_PROTOTYPE_VALUE_OF_NAME, EVAL_NAME, FUNCTION_NAME, FUNCTION_PROTOTYPE_APPLY_NAME,
    FUNCTION_PROTOTYPE_BIND_NAME, FUNCTION_PROTOTYPE_CALL_NAME, FUNCTION_PROTOTYPE_TO_STRING_NAME,
    GLOBAL_DECODE_URI_COMPONENT_NAME, GLOBAL_DECODE_URI_NAME, GLOBAL_ENCODE_URI_COMPONENT_NAME,
    GLOBAL_ENCODE_URI_NAME, GLOBAL_IS_FINITE_NAME, GLOBAL_IS_NAN_NAME, GLOBAL_PARSE_FLOAT_NAME,
    GLOBAL_PARSE_INT_NAME, JSON_IS_RAW_JSON_NAME, JSON_NAME, JSON_PARSE_NAME, JSON_RAW_JSON_NAME,
    JSON_STRINGIFY_NAME, MATH_ABS_NAME, MATH_ACOS_NAME, MATH_ACOSH_NAME, MATH_ASIN_NAME,
    MATH_ASINH_NAME, MATH_ATAN_NAME, MATH_ATAN2_NAME, MATH_ATANH_NAME, MATH_CBRT_NAME,
    MATH_CEIL_NAME, MATH_CLZ32_NAME, MATH_COS_NAME, MATH_COSH_NAME, MATH_EXP_NAME, MATH_EXPM1_NAME,
    MATH_F16ROUND_NAME, MATH_FLOOR_NAME, MATH_FROUND_NAME, MATH_HYPOT_NAME, MATH_IMUL_NAME,
    MATH_LOG_NAME, MATH_LOG1P_NAME, MATH_LOG2_NAME, MATH_LOG10_NAME, MATH_MAX_NAME, MATH_MIN_NAME,
    MATH_NAME, MATH_POW_NAME, MATH_RANDOM_NAME, MATH_ROUND_NAME, MATH_SIGN_NAME, MATH_SIN_NAME,
    MATH_SINH_NAME, MATH_SQRT_NAME, MATH_SUM_PRECISE_NAME, MATH_TAN_NAME, MATH_TANH_NAME,
    MATH_TRUNC_NAME, NUMBER_IS_FINITE_NAME, NUMBER_IS_INTEGER_NAME, NUMBER_IS_NAN_NAME,
    NUMBER_IS_SAFE_INTEGER_NAME, NUMBER_NAME, NUMBER_PROTOTYPE_TO_EXPONENTIAL_NAME,
    NUMBER_PROTOTYPE_TO_FIXED_NAME, NUMBER_PROTOTYPE_TO_LOCALE_STRING_NAME,
    NUMBER_PROTOTYPE_TO_PRECISION_NAME, NUMBER_PROTOTYPE_TO_STRING_NAME,
    NUMBER_PROTOTYPE_VALUE_OF_NAME, OBJECT_ASSIGN_NAME, OBJECT_CREATE_NAME,
    OBJECT_DEFINE_PROPERTIES_NAME, OBJECT_DEFINE_PROPERTY_NAME, OBJECT_ENTRIES_NAME,
    OBJECT_FREEZE_NAME, OBJECT_FROM_ENTRIES_NAME, OBJECT_GET_OWN_PROPERTY_DESCRIPTOR_NAME,
    OBJECT_GET_OWN_PROPERTY_DESCRIPTORS_NAME, OBJECT_GET_OWN_PROPERTY_NAMES_NAME,
    OBJECT_GET_OWN_PROPERTY_SYMBOLS_NAME, OBJECT_GET_PROTOTYPE_OF_NAME, OBJECT_HAS_OWN_NAME,
    OBJECT_IS_EXTENSIBLE_NAME, OBJECT_IS_FROZEN_NAME, OBJECT_IS_NAME, OBJECT_IS_SEALED_NAME,
    OBJECT_KEYS_NAME, OBJECT_NAME, OBJECT_PREVENT_EXTENSIONS_NAME, OBJECT_SEAL_NAME,
    OBJECT_SET_PROTOTYPE_OF_NAME, OBJECT_VALUES_NAME, PERFORMANCE_NAME, PERFORMANCE_NOW_NAME,
    PROMISE_CATCH_NAME, PROMISE_FINALLY_NAME, PROMISE_NAME, PROMISE_REJECT_NAME,
    PROMISE_RESOLVE_NAME, PROMISE_THEN_NAME, PROXY_NAME, PROXY_REVOCABLE_NAME, REFLECT_NAME,
    REGEXP_NAME, REGEXP_PROTOTYPE_EXEC_NAME, REGEXP_PROTOTYPE_TEST_NAME,
    REGEXP_PROTOTYPE_TO_STRING_NAME, SHARED_ARRAY_BUFFER_NAME, STRING_FROM_CHAR_CODE_NAME,
    STRING_FROM_CODE_POINT_NAME, STRING_NAME, STRING_PROTOTYPE_AT_NAME,
    STRING_PROTOTYPE_CHAR_AT_NAME, STRING_PROTOTYPE_CHAR_CODE_AT_NAME,
    STRING_PROTOTYPE_CODE_POINT_AT_NAME, STRING_PROTOTYPE_CONCAT_NAME,
    STRING_PROTOTYPE_ENDS_WITH_NAME, STRING_PROTOTYPE_INCLUDES_NAME,
    STRING_PROTOTYPE_INDEX_OF_NAME, STRING_PROTOTYPE_IS_WELL_FORMED_NAME,
    STRING_PROTOTYPE_ITERATOR_NAME, STRING_PROTOTYPE_LAST_INDEX_OF_NAME,
    STRING_PROTOTYPE_LOCALE_COMPARE_NAME, STRING_PROTOTYPE_MATCH_ALL_NAME,
    STRING_PROTOTYPE_MATCH_NAME, STRING_PROTOTYPE_NORMALIZE_NAME, STRING_PROTOTYPE_PAD_END_NAME,
    STRING_PROTOTYPE_PAD_START_NAME, STRING_PROTOTYPE_REPEAT_NAME,
    STRING_PROTOTYPE_REPLACE_ALL_NAME, STRING_PROTOTYPE_REPLACE_NAME, STRING_PROTOTYPE_SEARCH_NAME,
    STRING_PROTOTYPE_SLICE_NAME, STRING_PROTOTYPE_SPLIT_NAME, STRING_PROTOTYPE_STARTS_WITH_NAME,
    STRING_PROTOTYPE_SUBSTRING_NAME, STRING_PROTOTYPE_TO_LOCALE_LOWER_CASE_NAME,
    STRING_PROTOTYPE_TO_LOCALE_UPPER_CASE_NAME, STRING_PROTOTYPE_TO_LOWER_CASE_NAME,
    STRING_PROTOTYPE_TO_STRING_NAME, STRING_PROTOTYPE_TO_UPPER_CASE_NAME,
    STRING_PROTOTYPE_TO_WELL_FORMED_NAME, STRING_PROTOTYPE_TRIM_END_NAME,
    STRING_PROTOTYPE_TRIM_LEFT_NAME, STRING_PROTOTYPE_TRIM_NAME, STRING_PROTOTYPE_TRIM_RIGHT_NAME,
    STRING_PROTOTYPE_TRIM_START_NAME, STRING_PROTOTYPE_VALUE_OF_NAME, STRING_RAW_NAME, SYMBOL_NAME,
    SYMBOL_PROTOTYPE_TO_STRING_NAME, SYMBOL_PROTOTYPE_VALUE_OF_NAME,
};
pub(in crate::runtime) use function::{
    ASYNC_DISPOSABLE_STACK_NAME, ArrayBufferFunctionKind, AsyncDisposableStackFunctionKind,
    AtomicsFunctionKind, DATA_VIEW_NAME, DATE_NAME, DATE_NOW_NAME, DATE_PARSE_NAME, DATE_UTC_NAME,
    DISPOSABLE_STACK_NAME, DataViewFunctionKind, DateFunctionKind, DisposableStackFunctionKind,
    INTL_NAME, ITERATOR_NAME, IntlFunctionKind, IteratorFunctionKind, LocaleAccessorKind,
    LocaleMethodKind, NativeFunction, NativeFunctionKind, NativeFunctionRegistry,
    SHADOW_REALM_NAME, ShadowRealmFunctionKind, SharedArrayBufferFunctionKind, TEMPORAL_NAME,
    TemporalFunctionKind, TypedArrayFunctionKind,
};
pub(in crate::runtime) use function::{
    GLOBAL_THIS_NAME, INFINITY_NAME, NAN_NAME, OBJECT_PROTOTYPE_DEFINE_GETTER_NAME,
    OBJECT_PROTOTYPE_DEFINE_SETTER_NAME, OBJECT_PROTOTYPE_HAS_OWN_PROPERTY_NAME,
    OBJECT_PROTOTYPE_IS_PROTOTYPE_OF_NAME, OBJECT_PROTOTYPE_LOOKUP_GETTER_NAME,
    OBJECT_PROTOTYPE_LOOKUP_SETTER_NAME, OBJECT_PROTOTYPE_PROPERTY_IS_ENUMERABLE_NAME,
    OBJECT_PROTOTYPE_TO_LOCALE_STRING_NAME, OBJECT_PROTOTYPE_TO_STRING_NAME,
    OBJECT_PROTOTYPE_VALUE_OF_NAME, UNDEFINED_NAME,
};
pub(in crate::runtime::native) use function::{
    ITERATOR_CONCAT_NAME, ITERATOR_FROM_NAME, ITERATOR_PROTOTYPE_DROP_NAME,
    ITERATOR_PROTOTYPE_EVERY_NAME, ITERATOR_PROTOTYPE_FILTER_NAME, ITERATOR_PROTOTYPE_FIND_NAME,
    ITERATOR_PROTOTYPE_FLAT_MAP_NAME, ITERATOR_PROTOTYPE_FOR_EACH_NAME,
    ITERATOR_PROTOTYPE_MAP_NAME, ITERATOR_PROTOTYPE_REDUCE_NAME, ITERATOR_PROTOTYPE_SOME_NAME,
    ITERATOR_PROTOTYPE_TAKE_NAME, ITERATOR_PROTOTYPE_TO_ARRAY_NAME, ITERATOR_ZIP_KEYED_NAME,
    ITERATOR_ZIP_NAME,
};

pub(super) const OBJECT_CONSTRUCTOR_PROPERTY: &str = "constructor";
