mod builtins;
mod call_target;
mod core;
mod direct;
mod function;
mod kind;
mod registry;

pub(in crate::runtime::native) use builtins::number_intrinsic_property;
pub(in crate::runtime) use function::NativeFunction;
pub(in crate::runtime) use kind::NativeFunctionKind;
pub(in crate::runtime::native) use kind::{
    ARRAY_NAME, BOOLEAN_NAME, EVAL_NAME, FUNCTION_NAME, FUNCTION_PROTOTYPE_BIND_NAME,
    FUNCTION_PROTOTYPE_CALL_NAME, JSON_NAME, JSON_PARSE_NAME, JSON_STRINGIFY_NAME, MATH_ABS_NAME,
    MATH_ACOS_NAME, MATH_ACOSH_NAME, MATH_ASIN_NAME, MATH_ASINH_NAME, MATH_ATAN_NAME,
    MATH_ATAN2_NAME, MATH_ATANH_NAME, MATH_CBRT_NAME, MATH_CEIL_NAME, MATH_CLZ32_NAME,
    MATH_COS_NAME, MATH_COSH_NAME, MATH_EXP_NAME, MATH_EXPM1_NAME, MATH_FLOOR_NAME,
    MATH_FROUND_NAME, MATH_HYPOT_NAME, MATH_IMUL_NAME, MATH_LOG_NAME, MATH_LOG1P_NAME,
    MATH_LOG2_NAME, MATH_LOG10_NAME, MATH_MAX_NAME, MATH_MIN_NAME, MATH_NAME, MATH_POW_NAME,
    MATH_RANDOM_NAME, MATH_ROUND_NAME, MATH_SIGN_NAME, MATH_SIN_NAME, MATH_SINH_NAME,
    MATH_SQRT_NAME, MATH_TAN_NAME, MATH_TANH_NAME, MATH_TRUNC_NAME, NUMBER_NAME,
    OBJECT_DEFINE_PROPERTY_NAME, OBJECT_GET_OWN_PROPERTY_DESCRIPTOR_NAME,
    OBJECT_GET_OWN_PROPERTY_NAMES_NAME, OBJECT_GET_PROTOTYPE_OF_NAME, OBJECT_HAS_OWN_NAME,
    OBJECT_KEYS_NAME, OBJECT_NAME, PROMISE_CATCH_NAME, PROMISE_NAME, PROMISE_REJECT_NAME,
    PROMISE_RESOLVE_NAME, PROMISE_THEN_NAME, REGEXP_NAME, REGEXP_PROTOTYPE_TEST_NAME, STRING_NAME,
    SYMBOL_NAME,
};
pub(in crate::runtime) use kind::{
    INFINITY_NAME, NAN_NAME, OBJECT_PROTOTYPE_HAS_OWN_PROPERTY_NAME,
    OBJECT_PROTOTYPE_PROPERTY_IS_ENUMERABLE_NAME,
};
pub(in crate::runtime) use registry::NativeFunctionRegistry;

pub(super) const OBJECT_CONSTRUCTOR_PROPERTY: &str = "constructor";
