mod builtins;
mod core;
mod function;

pub(in crate::runtime::native) use builtins::number_intrinsic_property;
pub(in crate::runtime::native) use function::{
    ARRAY_NAME, BOOLEAN_NAME, EVAL_NAME, FUNCTION_NAME, FUNCTION_PROTOTYPE_BIND_NAME,
    FUNCTION_PROTOTYPE_CALL_NAME, GLOBAL_DECODE_URI_COMPONENT_NAME, GLOBAL_DECODE_URI_NAME,
    GLOBAL_ENCODE_URI_COMPONENT_NAME, GLOBAL_ENCODE_URI_NAME, GLOBAL_IS_FINITE_NAME,
    GLOBAL_IS_NAN_NAME, GLOBAL_PARSE_FLOAT_NAME, GLOBAL_PARSE_INT_NAME, JSON_NAME, JSON_PARSE_NAME,
    JSON_STRINGIFY_NAME, MATH_ABS_NAME, MATH_ACOS_NAME, MATH_ACOSH_NAME, MATH_ASIN_NAME,
    MATH_ASINH_NAME, MATH_ATAN_NAME, MATH_ATAN2_NAME, MATH_ATANH_NAME, MATH_CBRT_NAME,
    MATH_CEIL_NAME, MATH_CLZ32_NAME, MATH_COS_NAME, MATH_COSH_NAME, MATH_EXP_NAME, MATH_EXPM1_NAME,
    MATH_FLOOR_NAME, MATH_FROUND_NAME, MATH_HYPOT_NAME, MATH_IMUL_NAME, MATH_LOG_NAME,
    MATH_LOG1P_NAME, MATH_LOG2_NAME, MATH_LOG10_NAME, MATH_MAX_NAME, MATH_MIN_NAME, MATH_NAME,
    MATH_POW_NAME, MATH_RANDOM_NAME, MATH_ROUND_NAME, MATH_SIGN_NAME, MATH_SIN_NAME,
    MATH_SINH_NAME, MATH_SQRT_NAME, MATH_TAN_NAME, MATH_TANH_NAME, MATH_TRUNC_NAME,
    NUMBER_IS_FINITE_NAME, NUMBER_IS_NAN_NAME, NUMBER_NAME, OBJECT_ASSIGN_NAME, OBJECT_CREATE_NAME,
    OBJECT_DEFINE_PROPERTIES_NAME, OBJECT_DEFINE_PROPERTY_NAME, OBJECT_ENTRIES_NAME,
    OBJECT_GET_OWN_PROPERTY_DESCRIPTOR_NAME, OBJECT_GET_OWN_PROPERTY_DESCRIPTORS_NAME,
    OBJECT_GET_OWN_PROPERTY_NAMES_NAME, OBJECT_GET_PROTOTYPE_OF_NAME, OBJECT_HAS_OWN_NAME,
    OBJECT_IS_NAME, OBJECT_KEYS_NAME, OBJECT_NAME, OBJECT_SET_PROTOTYPE_OF_NAME,
    OBJECT_VALUES_NAME, PROMISE_CATCH_NAME, PROMISE_NAME, PROMISE_REJECT_NAME,
    PROMISE_RESOLVE_NAME, PROMISE_THEN_NAME, REGEXP_NAME, REGEXP_PROTOTYPE_TEST_NAME, STRING_NAME,
    STRING_PROTOTYPE_CHAR_AT_NAME, STRING_PROTOTYPE_CHAR_CODE_AT_NAME,
    STRING_PROTOTYPE_CONCAT_NAME, STRING_PROTOTYPE_ENDS_WITH_NAME, STRING_PROTOTYPE_INCLUDES_NAME,
    STRING_PROTOTYPE_INDEX_OF_NAME, STRING_PROTOTYPE_LAST_INDEX_OF_NAME,
    STRING_PROTOTYPE_REPEAT_NAME, STRING_PROTOTYPE_SLICE_NAME, STRING_PROTOTYPE_STARTS_WITH_NAME,
    STRING_PROTOTYPE_SUBSTRING_NAME, STRING_PROTOTYPE_TO_LOWER_CASE_NAME,
    STRING_PROTOTYPE_TO_UPPER_CASE_NAME, STRING_PROTOTYPE_TRIM_END_NAME,
    STRING_PROTOTYPE_TRIM_NAME, STRING_PROTOTYPE_TRIM_START_NAME, SYMBOL_NAME,
};
pub(in crate::runtime) use function::{
    GLOBAL_THIS_NAME, INFINITY_NAME, NAN_NAME, OBJECT_PROTOTYPE_HAS_OWN_PROPERTY_NAME,
    OBJECT_PROTOTYPE_PROPERTY_IS_ENUMERABLE_NAME,
};
pub(in crate::runtime) use function::{NativeFunction, NativeFunctionKind, NativeFunctionRegistry};

pub(super) const OBJECT_CONSTRUCTOR_PROPERTY: &str = "constructor";
