mod array;
mod array_buffer;
mod atomics;
mod bigint;
mod boolean;
mod data_view;
mod date;
mod eval;
mod function_constructor;
mod global;
mod group_by;
mod intl;
mod iterator;
mod iterator_consumers;
mod iterator_static;
mod iterator_stepping;
mod json;
mod json_meta;
mod json_raw;
mod map_modern;
mod map_set;
mod math;
mod math_sum_precise;
mod number;
mod number_format;
mod object;
mod object_prototype;
mod object_static;
mod performance;
mod promise;
mod proxy;
mod proxy_invariants;
mod reflect;
mod regexp;
mod set_operations;
mod shadow_realm;
mod shared_array_buffer;
mod species;
mod string;
mod string_annexb;
mod string_extra;
mod string_methods;
mod string_modern;
mod string_regexp;
mod symbol;
mod temporal;
mod typed_array;
mod weak_collections;

use crate::{error::Error, value::ErrorName};

pub(in crate::runtime::native) use iterator_consumers::IteratorConsumer;
pub(in crate::runtime::native) use map_set::{CollectionIterationTarget, MAP_NAME, SET_NAME};
pub(in crate::runtime::native) use number::number_intrinsic_property;
pub(in crate::runtime::native) use regexp::RegExpCallMode;
pub(in crate::runtime::native) use weak_collections::{WEAK_MAP_NAME, WEAK_SET_NAME};

fn dynamic_compilation_error(error: Error) -> Error {
    match error {
        error @ (Error::Lex { span, .. } | Error::Parse { span, .. }) => {
            Error::exception(ErrorName::SyntaxError, error.to_string()).with_runtime_span(span)
        }
        error @ (Error::Runtime { .. }
        | Error::JavaScript { .. }
        | Error::JavaScriptError { .. }
        | Error::ResourceLimit { .. }) => error,
    }
}

use super::{
    ARRAY_NAME, BIGINT_AS_INT_N_NAME, BIGINT_AS_UINT_N_NAME, BIGINT_NAME,
    BIGINT_PROTOTYPE_TO_LOCALE_STRING_NAME, BIGINT_PROTOTYPE_TO_STRING_NAME,
    BIGINT_PROTOTYPE_VALUE_OF_NAME, BOOLEAN_NAME, BOOLEAN_PROTOTYPE_TO_STRING_NAME,
    BOOLEAN_PROTOTYPE_VALUE_OF_NAME, EVAL_NAME, FUNCTION_NAME, FUNCTION_PROTOTYPE_APPLY_NAME,
    FUNCTION_PROTOTYPE_BIND_NAME, FUNCTION_PROTOTYPE_CALL_NAME, FUNCTION_PROTOTYPE_TO_STRING_NAME,
    GLOBAL_PARSE_FLOAT_NAME, GLOBAL_PARSE_INT_NAME, ITERATOR_FROM_NAME,
    ITERATOR_PROTOTYPE_DROP_NAME, ITERATOR_PROTOTYPE_EVERY_NAME, ITERATOR_PROTOTYPE_FILTER_NAME,
    ITERATOR_PROTOTYPE_FIND_NAME, ITERATOR_PROTOTYPE_FLAT_MAP_NAME,
    ITERATOR_PROTOTYPE_FOR_EACH_NAME, ITERATOR_PROTOTYPE_MAP_NAME, ITERATOR_PROTOTYPE_REDUCE_NAME,
    ITERATOR_PROTOTYPE_SOME_NAME, ITERATOR_PROTOTYPE_TAKE_NAME, ITERATOR_PROTOTYPE_TO_ARRAY_NAME,
    JSON_IS_RAW_JSON_NAME, JSON_NAME, JSON_PARSE_NAME, JSON_RAW_JSON_NAME, JSON_STRINGIFY_NAME,
    MATH_ABS_NAME, MATH_ACOS_NAME, MATH_ACOSH_NAME, MATH_ASIN_NAME, MATH_ASINH_NAME,
    MATH_ATAN_NAME, MATH_ATAN2_NAME, MATH_ATANH_NAME, MATH_CBRT_NAME, MATH_CEIL_NAME,
    MATH_CLZ32_NAME, MATH_COS_NAME, MATH_COSH_NAME, MATH_EXP_NAME, MATH_EXPM1_NAME,
    MATH_F16ROUND_NAME, MATH_FLOOR_NAME, MATH_FROUND_NAME, MATH_HYPOT_NAME, MATH_IMUL_NAME,
    MATH_LOG_NAME, MATH_LOG1P_NAME, MATH_LOG2_NAME, MATH_LOG10_NAME, MATH_MAX_NAME, MATH_MIN_NAME,
    MATH_NAME, MATH_POW_NAME, MATH_RANDOM_NAME, MATH_ROUND_NAME, MATH_SIGN_NAME, MATH_SIN_NAME,
    MATH_SINH_NAME, MATH_SQRT_NAME, MATH_SUM_PRECISE_NAME, MATH_TAN_NAME, MATH_TANH_NAME,
    MATH_TRUNC_NAME, NUMBER_IS_FINITE_NAME, NUMBER_IS_INTEGER_NAME, NUMBER_IS_NAN_NAME,
    NUMBER_IS_SAFE_INTEGER_NAME, NUMBER_NAME, NUMBER_PROTOTYPE_TO_EXPONENTIAL_NAME,
    NUMBER_PROTOTYPE_TO_FIXED_NAME, NUMBER_PROTOTYPE_TO_LOCALE_STRING_NAME,
    NUMBER_PROTOTYPE_TO_PRECISION_NAME, NUMBER_PROTOTYPE_TO_STRING_NAME,
    NUMBER_PROTOTYPE_VALUE_OF_NAME, NativeFunctionKind, OBJECT_ASSIGN_NAME,
    OBJECT_CONSTRUCTOR_PROPERTY, OBJECT_CREATE_NAME, OBJECT_DEFINE_PROPERTIES_NAME,
    OBJECT_DEFINE_PROPERTY_NAME, OBJECT_ENTRIES_NAME, OBJECT_FREEZE_NAME, OBJECT_FROM_ENTRIES_NAME,
    OBJECT_GET_OWN_PROPERTY_DESCRIPTOR_NAME, OBJECT_GET_OWN_PROPERTY_DESCRIPTORS_NAME,
    OBJECT_GET_OWN_PROPERTY_NAMES_NAME, OBJECT_GET_OWN_PROPERTY_SYMBOLS_NAME,
    OBJECT_GET_PROTOTYPE_OF_NAME, OBJECT_HAS_OWN_NAME, OBJECT_IS_EXTENSIBLE_NAME,
    OBJECT_IS_FROZEN_NAME, OBJECT_IS_NAME, OBJECT_IS_SEALED_NAME, OBJECT_KEYS_NAME, OBJECT_NAME,
    OBJECT_PREVENT_EXTENSIONS_NAME, OBJECT_PROTOTYPE_DEFINE_GETTER_NAME,
    OBJECT_PROTOTYPE_DEFINE_SETTER_NAME, OBJECT_PROTOTYPE_HAS_OWN_PROPERTY_NAME,
    OBJECT_PROTOTYPE_IS_PROTOTYPE_OF_NAME, OBJECT_PROTOTYPE_LOOKUP_GETTER_NAME,
    OBJECT_PROTOTYPE_LOOKUP_SETTER_NAME, OBJECT_PROTOTYPE_PROPERTY_IS_ENUMERABLE_NAME,
    OBJECT_PROTOTYPE_TO_LOCALE_STRING_NAME, OBJECT_PROTOTYPE_TO_STRING_NAME,
    OBJECT_PROTOTYPE_VALUE_OF_NAME, OBJECT_SEAL_NAME, OBJECT_SET_PROTOTYPE_OF_NAME,
    OBJECT_VALUES_NAME, PERFORMANCE_NAME, PERFORMANCE_NOW_NAME, PROMISE_CATCH_NAME,
    PROMISE_FINALLY_NAME, PROMISE_NAME, PROMISE_REJECT_NAME, PROMISE_RESOLVE_NAME,
    PROMISE_THEN_NAME, PROXY_REVOCABLE_NAME, REFLECT_NAME, REGEXP_NAME, REGEXP_PROTOTYPE_EXEC_NAME,
    REGEXP_PROTOTYPE_TEST_NAME, REGEXP_PROTOTYPE_TO_STRING_NAME, STRING_FROM_CHAR_CODE_NAME,
    STRING_FROM_CODE_POINT_NAME, STRING_NAME, STRING_PROTOTYPE_AT_NAME,
    STRING_PROTOTYPE_CHAR_AT_NAME, STRING_PROTOTYPE_CHAR_CODE_AT_NAME,
    STRING_PROTOTYPE_CODE_POINT_AT_NAME, STRING_PROTOTYPE_CONCAT_NAME,
    STRING_PROTOTYPE_ENDS_WITH_NAME, STRING_PROTOTYPE_INCLUDES_NAME,
    STRING_PROTOTYPE_INDEX_OF_NAME, STRING_PROTOTYPE_IS_WELL_FORMED_NAME,
    STRING_PROTOTYPE_ITERATOR_NAME, STRING_PROTOTYPE_LAST_INDEX_OF_NAME,
    STRING_PROTOTYPE_MATCH_ALL_NAME, STRING_PROTOTYPE_MATCH_NAME, STRING_PROTOTYPE_PAD_END_NAME,
    STRING_PROTOTYPE_PAD_START_NAME, STRING_PROTOTYPE_REPEAT_NAME,
    STRING_PROTOTYPE_REPLACE_ALL_NAME, STRING_PROTOTYPE_REPLACE_NAME, STRING_PROTOTYPE_SEARCH_NAME,
    STRING_PROTOTYPE_SLICE_NAME, STRING_PROTOTYPE_SPLIT_NAME, STRING_PROTOTYPE_STARTS_WITH_NAME,
    STRING_PROTOTYPE_SUBSTRING_NAME, STRING_PROTOTYPE_TO_LOCALE_LOWER_CASE_NAME,
    STRING_PROTOTYPE_TO_LOCALE_UPPER_CASE_NAME, STRING_PROTOTYPE_TO_LOWER_CASE_NAME,
    STRING_PROTOTYPE_TO_STRING_NAME, STRING_PROTOTYPE_TO_UPPER_CASE_NAME,
    STRING_PROTOTYPE_TO_WELL_FORMED_NAME, STRING_PROTOTYPE_TRIM_END_NAME,
    STRING_PROTOTYPE_TRIM_LEFT_NAME, STRING_PROTOTYPE_TRIM_NAME, STRING_PROTOTYPE_TRIM_RIGHT_NAME,
    STRING_PROTOTYPE_TRIM_START_NAME, STRING_PROTOTYPE_VALUE_OF_NAME, STRING_RAW_NAME, SYMBOL_NAME,
    SYMBOL_PROTOTYPE_TO_STRING_NAME, SYMBOL_PROTOTYPE_VALUE_OF_NAME,
};
