use crate::lexer::TokenKind;

pub(super) const fn keyword_property_name(kind: &TokenKind) -> Option<&'static str> {
    match kind {
        TokenKind::This => Some("this"),
        TokenKind::Let => Some("let"),
        TokenKind::Const => Some("const"),
        TokenKind::Var => Some("var"),
        TokenKind::If => Some("if"),
        TokenKind::Else => Some("else"),
        TokenKind::Do => Some("do"),
        TokenKind::While => Some("while"),
        TokenKind::For => Some("for"),
        TokenKind::Switch => Some("switch"),
        TokenKind::Case => Some("case"),
        TokenKind::Default => Some("default"),
        TokenKind::Class => Some("class"),
        TokenKind::Extends => Some("extends"),
        TokenKind::Break => Some("break"),
        TokenKind::Continue => Some("continue"),
        TokenKind::Debugger => Some("debugger"),
        TokenKind::Try => Some("try"),
        TokenKind::Catch => Some("catch"),
        TokenKind::Finally => Some("finally"),
        TokenKind::Throw => Some("throw"),
        TokenKind::Return => Some("return"),
        TokenKind::Function => Some("function"),
        TokenKind::Async => Some("async"),
        TokenKind::Await => Some("await"),
        TokenKind::Super => Some("super"),
        TokenKind::Import => Some("import"),
        TokenKind::Export => Some("export"),
        TokenKind::Enum => Some("enum"),
        TokenKind::With => Some("with"),
        TokenKind::New => Some("new"),
        TokenKind::In => Some("in"),
        TokenKind::InstanceOf => Some("instanceof"),
        TokenKind::Typeof => Some("typeof"),
        TokenKind::Void => Some("void"),
        TokenKind::Delete => Some("delete"),
        TokenKind::True => Some("true"),
        TokenKind::False => Some("false"),
        TokenKind::Null => Some("null"),
        _ => None,
    }
}
