#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "${script_dir}/.." && pwd)"
cd "${repo_root}"

fail() {
  printf 'publish-report-artifact: %s\n' "$*" >&2
  exit 1
}

need_cmd() {
  command -v "$1" >/dev/null 2>&1 || fail "missing required command: $1"
}

safe_source_metadata() {
  local metadata_file="$1"
  [[ -f "${metadata_file}" ]] || return 1
  # The file is generated by scripts/test-all.sh and contains simple KEY=value
  # assignments used to bind an artifact to the tested tree.
  # shellcheck disable=SC1090
  source "${metadata_file}"
}

valid_report_file() {
  local file_name="$1"
  [[ "${file_name}" =~ ^rsqjs-test-report-[0-9]{8}T[0-9]{6}Z\.md$ ]]
}

download_matching_artifact() {
  local repository="$1"
  local artifact_name="$2"
  local expected_tree="$3"
  local target_dir="$4"

  local artifact_lines
  artifact_lines="$(gh api "/repos/${repository}/actions/artifacts?name=${artifact_name}&per_page=100" \
    --jq '.artifacts | sort_by(.created_at) | reverse | .[] | select(.expired == false) | [.id, .workflow_run.id] | @tsv')"
  [[ -n "${artifact_lines}" ]] || fail "no non-expired artifact named '${artifact_name}'"

  local artifact_id run_id candidate metadata_file
  while IFS=$'\t' read -r artifact_id run_id; do
    [[ -n "${artifact_id}" && -n "${run_id}" ]] || continue
    candidate="${target_dir}/artifact-${artifact_id}"
    mkdir -p "${candidate}"
    if ! gh run download "${run_id}" --repo "${repository}" --name "${artifact_name}" --dir "${candidate}" >/dev/null; then
      printf 'skipping artifact %s from run %s: download failed\n' "${artifact_id}" "${run_id}" >&2
      continue
    fi
    metadata_file="${candidate}/rsqjs-report-metadata.env"
    if ! safe_source_metadata "${metadata_file}"; then
      printf 'skipping artifact %s: missing metadata\n' "${artifact_id}" >&2
      continue
    fi
    if [[ "${RSQJS_ARTIFACT_SCHEMA:-}" != "1" ]]; then
      printf 'skipping artifact %s: unsupported metadata schema\n' "${artifact_id}" >&2
      continue
    fi
    if [[ "${RSQJS_ARTIFACT_TREE_SHA:-}" != "${expected_tree}" ]]; then
      printf 'skipping artifact %s: tree mismatch\n' "${artifact_id}" >&2
      continue
    fi
    if [[ -z "${RSQJS_ARTIFACT_REPORT_FILE:-}" || -z "${RSQJS_ARTIFACT_REPORT_RELATIVE_PATH:-}" ]]; then
      printf 'skipping artifact %s: missing report path metadata\n' "${artifact_id}" >&2
      continue
    fi
    if ! valid_report_file "${RSQJS_ARTIFACT_REPORT_FILE}"; then
      printf 'skipping artifact %s: invalid report file name %s\n' "${artifact_id}" "${RSQJS_ARTIFACT_REPORT_FILE}" >&2
      continue
    fi
    if [[ ! -f "${candidate}/${RSQJS_ARTIFACT_REPORT_RELATIVE_PATH}" ]]; then
      printf 'skipping artifact %s: report file is absent\n' "${artifact_id}" >&2
      continue
    fi
    printf '%s\n' "${candidate}"
    return 0
  done <<< "${artifact_lines}"

  fail "no artifact named '${artifact_name}' matched tree ${expected_tree}"
}

checkout_latest_main() {
  git fetch --no-tags origin main
  if git show-ref --verify --quiet refs/heads/main; then
    git checkout main
    git merge --ff-only origin/main
  else
    git checkout -b main origin/main
  fi
}

fetch_tested_source_commit() {
  local source_commit="$1"
  local expected_tree="$2"

  if [[ ! "${source_commit}" =~ ^[0-9a-f]{40}$ ]]; then
    fail "invalid source commit in artifact metadata: ${source_commit}"
  fi

  git fetch --no-tags origin "${source_commit}"
  git cat-file -e "${source_commit}^{commit}" || fail "source commit is not a commit: ${source_commit}"

  local source_tree
  source_tree="$(git rev-parse "${source_commit}^{tree}")"
  if [[ "${source_tree}" != "${expected_tree}" ]]; then
    fail "source commit tree mismatch: ${source_tree} != ${expected_tree}"
  fi
}

archive_commit_message() {
  local source_commit="$1"
  local expected_tree="$2"
  local source_run="$3"

  printf 'Archive tested source %.12s [skip ci]\n\n' "${source_commit}"
  printf 'Source commit: %s\n' "${source_commit}"
  printf 'Source tree: %s\n' "${expected_tree}"
  printf 'Source workflow run: %s\n' "${source_run}"
}

checkout_archive_branch() {
  local archive_branch="$1"

  if git ls-remote --exit-code --heads origin "${archive_branch}" >/dev/null 2>&1; then
    git fetch --no-tags origin "${archive_branch}:refs/remotes/origin/${archive_branch}"
    git checkout -B "${archive_branch}" "refs/remotes/origin/${archive_branch}"
    return 0
  fi

  return 1
}

archive_tested_source_commit() {
  local archive_branch="$1"
  local source_commit="$2"
  local expected_tree="$3"
  local source_run="$4"

  git check-ref-format --branch "${archive_branch}" >/dev/null ||
    fail "invalid tested source archive branch: ${archive_branch}"
  fetch_tested_source_commit "${source_commit}" "${expected_tree}"

  local archive_message
  archive_message="$(archive_commit_message "${source_commit}" "${expected_tree}" "${source_run}")"

  if checkout_archive_branch "${archive_branch}"; then
    if git merge-base --is-ancestor "${source_commit}" HEAD; then
      printf 'tested source commit already archived: %s\n' "${source_commit}"
      return 0
    fi
    git merge --no-ff -s ours -m "${archive_message}" "${source_commit}"
  else
    git checkout -B "${archive_branch}" "${source_commit}"
    git commit --allow-empty -m "${archive_message}"
  fi

  git push origin "HEAD:refs/heads/${archive_branch}"
  printf 'tested source archive branch updated: %s -> %s\n' "${archive_branch}" "${source_commit}"
}

stage_report_outputs() {
  local source_report="$1"
  local report_file="$2"

  mkdir -p reports/test-runs
  local target_report="reports/test-runs/${report_file}"
  if [[ -f "${target_report}" ]] && ! cmp -s "${source_report}" "${target_report}"; then
    fail "tracked report already exists with different content: ${target_report}"
  fi
  cp "${source_report}" "${target_report}"

  cargo run --manifest-path runner/Cargo.toml -- --aggregate-reports reports/test-runs
  git add "${target_report}" reports/benchmark-rollup.md reports/benchmark-summary.jpg
}

commit_and_push() {
  local report_file="$1"
  local expected_tree="$2"
  local source_commit="$3"
  local source_run="$4"

  if git diff --cached --quiet; then
    printf 'canonical report outputs are already up to date\n'
    return 0
  fi

  local timestamp="${report_file#rsqjs-test-report-}"
  timestamp="${timestamp%.md}"
  git commit \
    -m "Add rsqjs report ${timestamp} [skip ci]" \
    -m "Source commit: ${source_commit}" \
    -m "Source tree: ${expected_tree}" \
    -m "Source workflow run: ${source_run}"

  if git push origin HEAD:main; then
    return 0
  fi

  printf 'initial report push failed; rebasing once onto latest origin/main\n' >&2
  git pull --rebase origin main
  cargo run --manifest-path runner/Cargo.toml -- --aggregate-reports reports/test-runs
  git add reports/benchmark-rollup.md reports/benchmark-summary.jpg
  if ! git diff --cached --quiet; then
    git commit --amend --no-edit
  fi
  git push origin HEAD:main
}

need_cmd gh
need_cmd git
need_cmd cargo

repository="${GITHUB_REPOSITORY:-}"
[[ -n "${repository}" ]] || fail "GITHUB_REPOSITORY is required"

merge_commit="${RSQJS_MERGE_COMMIT_SHA:-}"
[[ -n "${merge_commit}" ]] || fail "RSQJS_MERGE_COMMIT_SHA is required"

expected_tree="${RSQJS_EXPECTED_TREE_SHA:-}"
if [[ -z "${expected_tree}" ]]; then
  expected_tree="$(git rev-parse "${merge_commit}^{tree}")"
fi
artifact_name="${RSQJS_REPORT_ARTIFACT_NAME:-rsqjs-reports-${expected_tree}}"

tmp_dir="$(mktemp -d)"
trap 'rm -rf "${tmp_dir}"' EXIT

artifact_dir="$(download_matching_artifact "${repository}" "${artifact_name}" "${expected_tree}" "${tmp_dir}")"
metadata_file="${artifact_dir}/rsqjs-report-metadata.env"
safe_source_metadata "${metadata_file}" || fail "failed to read artifact metadata"

report_file="${RSQJS_ARTIFACT_REPORT_FILE}"
source_report="${artifact_dir}/${RSQJS_ARTIFACT_REPORT_RELATIVE_PATH}"
source_commit="${RSQJS_ARTIFACT_COMMIT_SHA:-unknown}"
source_run="${RSQJS_ARTIFACT_RUN_ID:-unknown}"
archive_branch="${RSQJS_TESTED_SOURCE_ARCHIVE_BRANCH:-ci-tested-sources}"

archive_tested_source_commit "${archive_branch}" "${source_commit}" "${expected_tree}" "${source_run}"
checkout_latest_main
stage_report_outputs "${source_report}" "${report_file}"
commit_and_push "${report_file}" "${expected_tree}" "${source_commit}" "${source_run}"
