#[cfg(not(feature = "std"))]
use crate::prelude::*;

use alloc::sync::Arc;

use super::{ErasedHostInstance, HostClass, HostInstance};
use crate::{Error, Result};

impl<T> HostInstance<T> {
    /// Moves this payload into shared ownership for a macro-backed class.
    ///
    /// The logical charge retains the caller-supplied payload size and adds
    /// the two reference counters owned by the `Arc` allocation.
    ///
    /// # Errors
    /// Fails when the logical payload charge overflows.
    pub fn into_shared(self) -> Result<HostInstance<Arc<T>>> {
        let counter_bytes = core::mem::size_of::<usize>()
            .checked_mul(2)
            .ok_or_else(|| Error::limit("shared host payload counter size overflowed"))?;
        let logical_payload_bytes = self
            .logical_payload_bytes
            .checked_add(counter_bytes)
            .ok_or_else(|| Error::limit("shared host payload size overflowed"))?;
        Ok(HostInstance {
            payload: Arc::new(self.payload),
            logical_payload_bytes,
            traced_values: self.traced_values,
        })
    }

    pub(super) fn erase(self) -> ErasedHostInstance
    where
        T: 'static,
    {
        ErasedHostInstance {
            payload: Box::new(self.payload),
            logical_payload_bytes: self.logical_payload_bytes,
            traced_values: self.traced_values,
        }
    }
}

/// Compile-time definition of one Rust-backed JavaScript class.
///
/// Implementations are normally generated by the `host_class` and
/// `host_methods` macros. Manual implementations remain supported when an
/// embedder needs custom registration logic.
pub trait HostClassDefinition: Sized + 'static {
    type Payload: 'static;

    fn host_class() -> HostClass<Self::Payload>;
}

/// Metadata and field descriptors generated from a macro-annotated struct.
///
/// This trait is public so generated code can reference it across crate
/// boundaries. Applications should implement [`HostClassDefinition`] instead.
#[doc(hidden)]
pub trait HostClassMetadata: Sized + 'static {
    const JS_CLASS_NAME: &'static str;
    const LOWER_CAMEL_CASE_MEMBERS: bool;

    fn install_fields(class: HostClass<Arc<Self>>) -> HostClass<Arc<Self>>;

    #[must_use]
    fn member_name(rust_name: &str) -> String {
        if !Self::LOWER_CAMEL_CASE_MEMBERS {
            return rust_name.to_owned();
        }
        let mut output = String::with_capacity(rust_name.len());
        let mut uppercase_next = false;
        for character in rust_name.chars() {
            if character == '_' {
                uppercase_next = true;
            } else if uppercase_next {
                output.extend(character.to_uppercase());
                uppercase_next = false;
            } else {
                output.push(character);
            }
        }
        output
    }
}
