use crate::SourceSpan;

#[derive(Debug, Clone, PartialEq)]
pub struct Token {
    pub kind: TokenKind,
    pub span: SourceSpan,
    pub line_terminator_before: bool,
    pub identifier_escaped: bool,
}

impl Token {
    pub const fn offset(&self) -> usize {
        self.span.start()
    }
}

#[derive(Debug, Clone, PartialEq)]
pub enum TokenKind {
    Number(f64),
    String(String),
    TemplateHead(String),
    TemplateMiddle(String),
    TemplateTail(String),
    RegExp { pattern: String, flags: String },
    Identifier(String),
    Let,
    Const,
    Var,
    If,
    Else,
    Do,
    While,
    For,
    Switch,
    Case,
    Default,
    Class,
    Extends,
    Break,
    Continue,
    Debugger,
    Try,
    Catch,
    Finally,
    Throw,
    Return,
    Function,
    Async,
    Await,
    Super,
    Import,
    Export,
    Enum,
    With,
    New,
    This,
    In,
    InstanceOf,
    Typeof,
    Void,
    Delete,
    True,
    False,
    Null,
    Undefined,
    Plus,
    PlusPlus,
    PlusEqual,
    Minus,
    MinusMinus,
    MinusEqual,
    Star,
    StarStar,
    StarEqual,
    StarStarEqual,
    Slash,
    SlashEqual,
    Percent,
    PercentEqual,
    Bang,
    Tilde,
    Arrow,
    Equal,
    EqualEqual,
    BangEqual,
    StrictEqual,
    StrictNotEqual,
    Less,
    LessEqual,
    LessLess,
    LessLessEqual,
    Greater,
    GreaterEqual,
    GreaterGreater,
    GreaterGreaterEqual,
    GreaterGreaterGreater,
    GreaterGreaterGreaterEqual,
    Ampersand,
    AmpersandEqual,
    Pipe,
    PipeEqual,
    Caret,
    CaretEqual,
    AndAnd,
    AndAndEqual,
    OrOr,
    OrOrEqual,
    QuestionQuestion,
    QuestionQuestionEqual,
    Question,
    Colon,
    Dot,
    DotDotDot,
    LParen,
    RParen,
    LBrace,
    RBrace,
    LBracket,
    RBracket,
    Semicolon,
    Comma,
    Eof,
}
