use crate::{Error, SourceSpan, value::JsBigInt};

#[derive(Debug, Clone, PartialEq)]
pub struct Token {
    pub kind: TokenKind,
    pub span: SourceSpan,
    pub line_terminator_before: bool,
    pub identifier_escaped: bool,
}

impl Token {
    pub const fn offset(&self) -> usize {
        self.span.start()
    }
}

#[derive(Debug, Clone, PartialEq)]
pub enum TokenKind {
    #[doc(hidden)]
    LexicalError(Box<Error>),
    Number(f64),
    BigInt(JsBigInt),
    String(Vec<u16>),
    TemplateHead(Vec<u16>),
    TemplateMiddle(Vec<u16>),
    TemplateTail(Vec<u16>),
    RegExp {
        pattern: String,
        flags: String,
    },
    Identifier(String),
    /// A `#name` private identifier; the text keeps its leading `#` so
    /// private names can never collide with public identifier names.
    PrivateName(String),
    Let,
    Const,
    Var,
    If,
    Else,
    Do,
    While,
    For,
    Switch,
    Case,
    Default,
    Class,
    Extends,
    Break,
    Continue,
    Debugger,
    Try,
    Catch,
    Finally,
    Throw,
    Return,
    Function,
    Async,
    Await,
    Super,
    Import,
    Export,
    Enum,
    With,
    New,
    This,
    In,
    InstanceOf,
    Typeof,
    Void,
    Delete,
    True,
    False,
    Null,
    Plus,
    PlusPlus,
    PlusEqual,
    Minus,
    MinusMinus,
    MinusEqual,
    Star,
    StarStar,
    StarEqual,
    StarStarEqual,
    Slash,
    SlashEqual,
    Percent,
    PercentEqual,
    Bang,
    Tilde,
    Arrow,
    Equal,
    EqualEqual,
    BangEqual,
    StrictEqual,
    StrictNotEqual,
    Less,
    LessEqual,
    LessLess,
    LessLessEqual,
    Greater,
    GreaterEqual,
    GreaterGreater,
    GreaterGreaterEqual,
    GreaterGreaterGreater,
    GreaterGreaterGreaterEqual,
    Ampersand,
    AmpersandEqual,
    Pipe,
    PipeEqual,
    Caret,
    CaretEqual,
    AndAnd,
    AndAndEqual,
    OrOr,
    OrOrEqual,
    QuestionQuestion,
    QuestionQuestionEqual,
    Question,
    Colon,
    Dot,
    DotDotDot,
    LParen,
    RParen,
    LBrace,
    RBrace,
    LBracket,
    RBracket,
    Semicolon,
    Comma,
    Eof,
}
