use std::{fs, path::Path};

use anyhow::Context as _;
use tabled::Table;

use super::{BUDGET_LABEL, JetStreamReport};
use crate::{RUNNER_NAME, fenced_table, report_metadata, timing};

pub fn render_section(report: &JetStreamReport) -> Vec<String> {
    vec![
        "## JetStream Shell Benchmarks".to_owned(),
        String::new(),
        summary(report),
        String::new(),
        fenced_table(&Table::new(&report.rows)),
        String::new(),
    ]
}

pub fn write_report(
    path: &Path,
    metadata: &report_metadata::RunMetadata,
    report: &JetStreamReport,
) -> anyhow::Result<()> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).with_context(|| {
            format!(
                "failed to create JetStream report directory '{}'",
                parent.display()
            )
        })?;
    }
    fs::write(path, render_markdown(metadata, report))
        .with_context(|| format!("failed to write JetStream report '{}'", path.display()))?;
    println!("JetStream shell benchmark report: {}", path.display());
    Ok(())
}

fn render_markdown(metadata: &report_metadata::RunMetadata, report: &JetStreamReport) -> String {
    let mut sections = vec![
        "# Velum JetStream Shell Benchmark Report".to_owned(),
        String::new(),
        format!("Generated by {RUNNER_NAME}."),
        String::new(),
    ];
    sections.extend(report_metadata::render_section(metadata));
    sections.extend(render_section(report));
    sections.join("\n")
}

fn summary(report: &JetStreamReport) -> String {
    format!(
        "- Measured: {}\n- Failed candidates: {}\n- Invalid measurements: {}\n- Skipped: {}\n- Missing or stale QuickJS baseline: {}\n- Over latency budget ({}): {}\n- Elapsed: {}",
        report.measured,
        report.failed,
        report.invalid,
        report.skipped,
        report.reference_missing,
        BUDGET_LABEL,
        report.over_latency_budget,
        timing::format_duration(report.elapsed),
    )
}
