use std::{collections::BTreeMap, time::Duration};

use tabled::{Table, Tabled};

use super::{
    CaseRow, CorpusReport, FeatureAreaRow, FeatureAreaStats, FullReport, REPORT_TITLE, RUNNER_NAME,
    STATUS_FAILED, STATUS_PASSED, STATUS_SKIPPED, SkipReasonRow, benchmarks,
    failure_classification, jetstream, report_text, timing,
};

const NO_FAILED_CASES: &str = "No failed cases.";
const TEST262_FULL_CORPUS_NAME: &str = "Test262 full corpus";
const FAILED_CASE_DETAIL_LIMIT: usize = 30;
const CORPUS_TIMING_ROW_LIMIT: usize = 200;
const FEATURE_AREA_ROW_LIMIT: usize = 40;
const BASIS_POINTS_SCALE: usize = 10_000;
const PERCENT_SCALE: usize = 100;
const COVERAGE_SCALE: usize = 1_000_000;
const COVERAGE_MINOR_SCALE: usize = 10_000;
const OTHER_FEATURE_AREAS: &str = "other feature areas";
const NO_SKIP_REASON: &str = "none";
const MILLISECONDS_PER_SECOND: f64 = 1_000.0;

#[derive(Debug, Tabled)]
struct CorpusSummaryRow {
    corpus: String,
    total: usize,
    executed: usize,
    passed: String,
    failed: String,
    skipped: String,
    coverage: String,
    pass_rate: String,
    elapsed: String,
}

#[derive(Debug, Clone, Tabled)]
struct CaseDetailRow {
    case: String,
    status: String,
    source: String,
    elapsed: String,
    detail: String,
}

#[derive(Debug, Clone, Tabled)]
struct CaseTimingRow {
    case: String,
    status: String,
    source: String,
    elapsed: String,
}

#[derive(Debug, Tabled)]
struct TimingSummaryRow {
    phase: String,
    rows: usize,
    elapsed: String,
}

pub fn render_report(report: &FullReport) -> String {
    let mut sections = vec![
        REPORT_TITLE.to_owned(),
        String::new(),
        format!("Generated by {RUNNER_NAME}."),
        String::new(),
    ];
    sections.extend(super::report_metadata::render_section(&report.metadata));
    sections.extend([
        "Corpus failure sections list failed cases only. Timing sections list recorded case timings, capped to the slowest rows for large corpora.".to_owned(),
        "The sibling `*-timings.tsv` artifact lists every recorded test, benchmark, and JetStream timing row.".to_owned(),
        "The full Test262 corpus is progress-only; the active subset remains the CI gate.".to_owned(),
        "Test262 file conformance collapses required variants by source file for dashboard comparison.".to_owned(),
        "Test262 full corpus keeps default, strict, module, and raw variants as diagnostic rows.".to_owned(),
        String::new(),
        "## Runner Timing Summary".to_owned(),
        String::new(),
        fenced_table(&Table::new(timing_summary_rows(report))),
        String::new(),
        "## Corpus Summary".to_owned(),
        String::new(),
        fenced_table(&Table::new(corpus_summary_rows(report))),
    ]);
    for corpus in &report.corpora {
        sections.push(format!("## {}", corpus.name));
        sections.push(String::new());
        sections.push(format!(
            "- Total: {}\n- Executed: {}\n- Passed: {}\n- Failed: {}\n- Skipped: {}\n- Coverage: {}\n- Pass rate: {}",
            corpus.total(),
            corpus.executed(),
            corpus.passed(),
            corpus.failed(),
            corpus.skipped(),
            coverage_percent(corpus.executed(), corpus.total()),
            percent(corpus.passed(), corpus.executed()),
        ));
        sections.push(format!(
            "- Elapsed: {}",
            timing::format_duration(corpus.elapsed)
        ));
        render_skip_reasons(&mut sections, corpus);
        render_feature_map(&mut sections, corpus);
        sections.push(String::new());
        render_case_timings(&mut sections, corpus);
        let failed_rows = corpus.failed_rows();
        if corpus.name == TEST262_FULL_CORPUS_NAME {
            sections.extend(failure_classification::sections(&failed_rows));
        }
        render_failed_cases(&mut sections, &failed_rows);
    }
    sections.push("## Benchmarks".to_owned());
    sections.push(String::new());
    sections.push(format!(
        "- Measured: {}\n- In-process measured: {}\n- Failed: {}\n- Invalid: {}\n- Skipped reference: {}\n- Over latency budget ({}): {}\n- Over memory budget ({}): {}\n- Elapsed: {}",
        report.benchmarks.measured,
        report.benchmarks.in_process_measured,
        report.benchmarks.failed,
        report.benchmarks.invalid,
        report.benchmarks.skipped,
        benchmarks::BUDGET_LABEL,
        report.benchmarks.over_latency_budget,
        benchmarks::BUDGET_LABEL,
        report.benchmarks.over_memory_budget,
        timing::format_duration(report.benchmarks.elapsed),
    ));
    sections.push(String::new());
    sections.push(fenced_table(&Table::new(&report.benchmarks.rows)));
    sections.push(String::new());
    sections.extend(jetstream::render_section(&report.jetstream));
    sections.join("\n")
}

pub fn render_timing_tsv(report: &FullReport) -> String {
    let mut body = String::new();
    push_tsv_row(
        &mut body,
        &[
            "kind",
            "phase",
            "case",
            "status",
            "source",
            "iterations",
            "case_elapsed",
            "rsqjs_measure",
            "quickjs_measure",
            "detail",
        ],
    );
    for corpus in &report.corpora {
        for row in &corpus.rows {
            let elapsed = duration_millis(row.elapsed);
            push_tsv_row(
                &mut body,
                &[
                    "test",
                    corpus.name,
                    &row.case,
                    &row.status,
                    &row.source,
                    "",
                    &elapsed,
                    "",
                    "",
                    &row.detail,
                ],
            );
        }
    }
    for row in &report.benchmarks.rows {
        let iterations = row.iterations.to_string();
        push_tsv_row(
            &mut body,
            &[
                "benchmark",
                "Benchmarks",
                &row.benchmark,
                &row.status,
                &row.source,
                &iterations,
                &row.case_elapsed,
                &row.rsqjs_measure,
                &row.quickjs_measure,
                &row.detail,
            ],
        );
    }
    for row in &report.jetstream.rows {
        push_tsv_row(
            &mut body,
            &[
                "jetstream",
                "JetStream Shell Benchmarks",
                &row.benchmark,
                &row.status,
                &row.source,
                "",
                &row.case_elapsed,
                &row.rsqjs_measure,
                &row.quickjs_measure,
                &row.detail,
            ],
        );
    }
    body
}

fn push_tsv_row(body: &mut String, fields: &[&str]) {
    let mut first = true;
    for field in fields {
        if first {
            first = false;
        } else {
            body.push('\t');
        }
        push_tsv_field(body, field);
    }
    body.push('\n');
}

fn push_tsv_field(body: &mut String, field: &str) {
    for character in field.chars() {
        match character {
            '\t' | '\n' | '\r' => body.push(' '),
            _ => body.push(character),
        }
    }
}

fn duration_millis(duration: Duration) -> String {
    format!("{:.6}", duration.as_secs_f64() * MILLISECONDS_PER_SECOND)
}

fn render_skip_reasons(sections: &mut Vec<String>, corpus: &CorpusReport) {
    if corpus.skip_reasons.is_empty() {
        return;
    }
    sections.push(String::new());
    sections.push("### Skip Reasons".to_owned());
    sections.push(String::new());
    sections.push(fenced_table(&Table::new(&corpus.skip_reasons)));
}

fn render_feature_map(sections: &mut Vec<String>, corpus: &CorpusReport) {
    if corpus.feature_areas.is_empty() {
        return;
    }
    sections.push(String::new());
    sections.push("### Feature Map".to_owned());
    sections.push(String::new());
    sections.push(
        "Feature areas aggregate Test262 variants by source path. Passed and skipped cases are summarized, not listed."
            .to_owned(),
    );
    sections.push(String::new());
    sections.push(fenced_table(&Table::new(&corpus.feature_areas)));
}

fn render_case_timings(sections: &mut Vec<String>, corpus: &CorpusReport) {
    let timing_rows = case_timing_rows(corpus);
    if timing_rows.is_empty() {
        return;
    }
    sections.push("### Case Timings".to_owned());
    sections.push(String::new());
    let recorded = recorded_timing_count(corpus);
    if timing_rows.len() < recorded {
        sections.push(format!(
            "Showing the slowest {} of {} recorded case timings.",
            timing_rows.len(),
            recorded
        ));
        sections.push(String::new());
    }
    sections.push(fenced_table(&Table::new(&timing_rows)));
    sections.push(String::new());
}

fn render_failed_cases(sections: &mut Vec<String>, failed_rows: &[CaseRow]) {
    sections.push("### Failed Cases".to_owned());
    sections.push(String::new());
    if failed_rows.is_empty() {
        sections.push(NO_FAILED_CASES.to_owned());
        return;
    }
    let displayed_failed_rows = last_failed_rows(failed_rows, FAILED_CASE_DETAIL_LIMIT);
    if displayed_failed_rows.len() < failed_rows.len() {
        sections.push(format!(
            "Showing the last {} of {} failed cases.",
            displayed_failed_rows.len(),
            failed_rows.len()
        ));
        sections.push(String::new());
    }
    sections.push(fenced_table(&Table::new(case_detail_rows(
        &displayed_failed_rows,
    ))));
}

fn last_failed_rows(rows: &[CaseRow], limit: usize) -> Vec<CaseRow> {
    let skip = rows.len().saturating_sub(limit);
    rows.iter().skip(skip).cloned().collect()
}

fn timing_summary_rows(report: &FullReport) -> Vec<TimingSummaryRow> {
    let mut rows = vec![TimingSummaryRow {
        phase: "Full runner report".to_owned(),
        rows: report
            .corpora
            .iter()
            .map(CorpusReport::total)
            .fold(0usize, usize::saturating_add)
            .saturating_add(report.benchmarks.rows.len())
            .saturating_add(report.jetstream.rows.len()),
        elapsed: timing::format_duration(report.elapsed),
    }];
    rows.extend(report.corpora.iter().map(|corpus| TimingSummaryRow {
        phase: corpus.name.to_owned(),
        rows: corpus.total(),
        elapsed: timing::format_duration(corpus.elapsed),
    }));
    rows.push(TimingSummaryRow {
        phase: "Benchmarks".to_owned(),
        rows: report.benchmarks.rows.len(),
        elapsed: timing::format_duration(report.benchmarks.elapsed),
    });
    rows.push(TimingSummaryRow {
        phase: "JetStream Shell Benchmarks".to_owned(),
        rows: report.jetstream.rows.len(),
        elapsed: timing::format_duration(report.jetstream.elapsed),
    });
    rows
}

fn corpus_summary_rows(report: &FullReport) -> Vec<CorpusSummaryRow> {
    report
        .corpora
        .iter()
        .map(|corpus| CorpusSummaryRow {
            corpus: corpus.name.to_owned(),
            total: corpus.total(),
            executed: corpus.executed(),
            passed: format!("{} {}", corpus.passed(), STATUS_PASSED),
            failed: format!("{} {}", corpus.failed(), STATUS_FAILED),
            skipped: format!("{} {}", corpus.skipped(), STATUS_SKIPPED),
            coverage: coverage_percent(corpus.executed(), corpus.total()),
            pass_rate: percent(corpus.passed(), corpus.executed()),
            elapsed: timing::format_duration(corpus.elapsed),
        })
        .collect()
}

fn recorded_timing_count(corpus: &CorpusReport) -> usize {
    corpus
        .rows
        .iter()
        .filter(|row| row.elapsed > Duration::ZERO)
        .count()
}

fn case_timing_rows(corpus: &CorpusReport) -> Vec<CaseTimingRow> {
    let mut rows = corpus
        .rows
        .iter()
        .filter(|row| row.elapsed > Duration::ZERO)
        .collect::<Vec<_>>();
    rows.sort_by(|left, right| {
        right
            .elapsed
            .cmp(&left.elapsed)
            .then_with(|| left.case.cmp(&right.case))
    });
    rows.into_iter()
        .take(CORPUS_TIMING_ROW_LIMIT)
        .map(|row| CaseTimingRow {
            case: row.case.clone(),
            status: row.status.clone(),
            source: row.source.clone(),
            elapsed: timing::format_duration(row.elapsed),
        })
        .collect()
}

fn case_detail_rows(rows: &[CaseRow]) -> Vec<CaseDetailRow> {
    rows.iter()
        .map(|row| CaseDetailRow {
            case: row.case.clone(),
            status: row.status.clone(),
            source: row.source.clone(),
            elapsed: timing::format_duration(row.elapsed),
            detail: report_text::table_detail(&row.detail),
        })
        .collect()
}

pub fn skip_reason_rows(rows: &[CaseRow]) -> Vec<SkipReasonRow> {
    let mut reasons = BTreeMap::<String, usize>::new();
    for row in rows {
        if row.status == STATUS_SKIPPED {
            let count = reasons.entry(row.detail.clone()).or_default();
            *count = count.saturating_add(1);
        }
    }
    reasons
        .into_iter()
        .map(|(reason, skipped)| SkipReasonRow {
            skipped,
            reason: report_text::table_detail(&reason),
        })
        .collect()
}

pub fn feature_area_rows(stats: Vec<FeatureAreaStats>) -> Vec<FeatureAreaRow> {
    feature_area_rows_with_limit(stats, FEATURE_AREA_ROW_LIMIT)
}

pub fn feature_area_rows_with_limit(
    mut stats: Vec<FeatureAreaStats>,
    limit: usize,
) -> Vec<FeatureAreaRow> {
    stats.sort_by(|left, right| {
        right
            .total
            .cmp(&left.total)
            .then_with(|| right.failed.cmp(&left.failed))
            .then_with(|| left.feature_area.cmp(&right.feature_area))
    });

    let mut rows = Vec::new();
    let mut remainder = FeatureAreaStats::new(OTHER_FEATURE_AREAS.to_owned());
    for (index, area) in stats.into_iter().enumerate() {
        if index < limit {
            rows.push(feature_area_row(&area));
        } else {
            remainder.merge(area);
        }
    }
    if remainder.total > 0 {
        rows.push(feature_area_row(&remainder));
    }
    rows
}

fn feature_area_row(stats: &FeatureAreaStats) -> FeatureAreaRow {
    let executed = stats.executed();
    FeatureAreaRow {
        feature_area: stats.feature_area.clone(),
        total: stats.total,
        executed,
        passed: format!("{} {}", stats.passed, STATUS_PASSED),
        failed: format!("{} {}", stats.failed, STATUS_FAILED),
        skipped: format!("{} {}", stats.skipped, STATUS_SKIPPED),
        pass_rate: percent(stats.passed, executed),
        manifest_enabled: stats.manifest_enabled,
        top_skip_reason: top_skip_reason(stats),
    }
}

fn top_skip_reason(stats: &FeatureAreaStats) -> String {
    let mut best = None::<(&String, usize)>;
    for (reason, skipped) in &stats.skip_reasons {
        let skipped = *skipped;
        let replace = match best {
            None => true,
            Some((best_reason, best_skipped)) => {
                skipped > best_skipped || skipped == best_skipped && reason < best_reason
            }
        };
        if replace {
            best = Some((reason, skipped));
        }
    }
    if let Some((reason, skipped)) = best {
        return format!("{skipped}: {}", report_text::table_detail(reason));
    }
    NO_SKIP_REASON.to_owned()
}

pub fn fenced_table(table: &Table) -> String {
    format!("```text\n{table}\n```")
}

pub fn percent(part: usize, total: usize) -> String {
    if total == 0 {
        return "0.00%".to_owned();
    }
    let basis_points = part.saturating_mul(BASIS_POINTS_SCALE) / total;
    let major = basis_points / PERCENT_SCALE;
    let minor = basis_points % PERCENT_SCALE;
    format!("{major}.{minor:02}%")
}

pub fn coverage_percent(part: usize, total: usize) -> String {
    if total == 0 {
        return "0.0000%".to_owned();
    }
    let scaled = part.saturating_mul(COVERAGE_SCALE) / total;
    let major = scaled / COVERAGE_MINOR_SCALE;
    let minor = scaled % COVERAGE_MINOR_SCALE;
    format!("{major}.{minor:04}%")
}
